fastify/point-of-view

README.md, example.js, index.js, package.json, templates/index.ejs, templates/index.html, templates/index.pug, test.js
As titled, this is the very first implementation of the template plugin.
I've created a PR instead of push directly the code to master to discuss which is the best implementation.
@mcollina feedbacks? :)
=> First implementation

README.md, index.js, package.json, templates/index.njk, test.js
I like nunjucks template engine and found no support in fastify/point-of-view, so I added support and test cases for nunjucks template engine. All test cases have been passed.
=> Added support and test cases for nunjucks template engine.

.gitignore, README.md, example-ejs-with-some-options.js, package.json, tap-snapshots/test-with-snapshot.js-TAP.test.js, tap-snapshots/test.js-TAP.test.js, templates/fragment-footer.html, templates/fragment-header.ejs, templates/index-with-includes.ejs, test-with-snapshot.js, test.js
Hi, after the rebase this is the same update of the previous PR, see [PR26](https://github.com/fastify/point-of-view/pull/26).
I'll add other commits later to add a test, as requested.
Thanks for the help and the patience :-) , 
Sandro
=> Issue20 - update README to clarify include usage with ejs - second try

.gitignore, example-ejs-with-some-options.js, index.js, package.json, tap-snapshots/test-with-snapshot.js-TAP.test.js, templates/fragment-footer.html, templates/index-with-includes-and-attribute-missing.ejs, templates/index-with-includes-one-missing.ejs, templates/index.ejs, test-with-snapshot.js, test.js
Hi all, this is the implementation of the fix.
Due to lack of time now it's without tests but I'll add them in a few days.
I published now so maybe in the meantime someone could do some initial review and feedback.
Thanks for now. Bye
=> Issue 32, ejs templates using a not existing include or a page attribute missing

package.json
Remember to update plugin release after this PR :-) ...
=> chore(package): update nunjucks to version 3.1.2

test-with-snapshot.js, test.js
As titled :)
(possibly linked to https://github.com/fastify/fastify/issues/913 and https://github.com/fastify/fastify/pull/1082)
=> Resolves #69

.travis.yml, tap-snapshots/test-with-snapshot.js-TAP.test.js, test-with-snapshot.js
Added win build, remove node 9
=> Update tests for windows

index.d.ts, package.json, tsconfig.json, types.test.ts
=>  Add TypeScript definitions

package.json
=> chore(package): update nunjucks to version 3.1.6

README.md
=> Update ejs link

package.json, types.test.ts
Updated all dependencies to latest (no ejs-mate for now) and fix TypeScript types.
Note that the only dependency not upgraded to latest (major) is ejs-mate: with latest 2.x (2.3.0) all works, while with latest 3.x (3.0.0) it seems that variables passed to views are not seem, so some test is broken.
If it's good enough for you, I think you could merge as is (and maybe publish as a new release).
So after I can try to address that, with another PR (more time will be needed probably).
Tell me.
Thanks, Sandro
=> Updated all dependencies to latest (no ejs-mate for now)

README.md, index.js, templates/index-with-global.njk, test.js
To be able to add filter, extensions, etc... on Nunjunks environment
=> Add Nunjunks renderer onConfigure option

package.json
=> chore(package): update @types/node to version 11.11.3

README.md, index.js, package.json, templates/footer.art, templates/header.art, templates/index.art, test.js
=> add art-template support

README.md, index.js, test.js
=> feat: add default engine data

index.js, test/test-art-template.js
=> fix:support await fastify.view mode with art-template

index.js
This improves performance significantly (got up to 20x).
=> Precompile Handlebars templates and partials

example-async.js, package.json
Fixes https://github.com/fastify/point-of-view/issues/82
=> async example

.gitignore, index.d.ts, types.test.ts
https://github.com/fastify/point-of-view/issues/142
=> Add missing props for options in TS declaration file

.dependabot/config.yml, .github/workflows/ci.yml, .travis.yml, README.md
=> Move to dependabot and github actions.

README.md, example-async.js, index.js, test/test.js
=> make reply view result thenable

README.md, index.js, package.json, templates/index-with-custom-tag.liquid, templates/index.liquid, test/test-liquid.js
=> feat: support liquidjs (#172)

index.js, test/test-marko.js, test/test-nunjucks.js
-fixed render methods for nunjucks and marko
-added tests
- no documentation needed
=> Bugfix for #176

index.d.ts
Hi! This adds the dot engine option to the PointOfViewOptions interface to get the TypeScript build for doT fully working.
=> Add dot engine option to PointOfViewOptions

.dependabot/config.yml, .github/dependabot.yml, .github/workflows/ci.yml
=> Dependabot auto-merge

README.md, index.js, test/test.js
Pull request for the following feature mentioned here: https://github.com/fastify/point-of-view/issues/201
Please let me know if there's anything you would like changed, as it's my first time contributing to fastify.
Thank you :)
=> Add clearCache feature to fastify.view

templates/index.marko
Yo, while I was poking around I found a .marko template which is no longer used since marko support was dropped. So I deleted it!
Ta!
=> chore: delete unused marko template

README.md
=> doc: add mention to v5 for Fastify 3.x

types/index.d.ts, types/index.test-d.ts
=> types: add view property to FastifyInstance

README.md
=> docs(readme): add maxCache option description

index.js, templates/index.eta, test/test-eta.js
This will fix https://github.com/fastify/point-of-view/issues/346
=> catch async errors

index.js, test/test.js
Fixes https://github.com/fastify/point-of-view/issues/349
Second try at this, borked my keys and commit wasn't showing as signed correctly :(
=> decorate reply with locals and add on request hook to default to empty object

index.js
https://github.com/fastify/fastify/issues/5031
=> prefer `request.routeOptions.url`

types/index.d.ts
not critical and not really making a difference, but for correctness.
=> chore: use FastifyPluginAsync in types
