- .gitignore
- README.md
- benchmark/express.js
- benchmark/fastify.js
- index.js
- package.json
- templates/index.marko
- test.js
As titled.
The benchmark are very promising, with `Marko` we gain at least 1000 request per second compared to `ejs` :)
Feedbacks?
cc @mcollina @jsumners @patrick-steele-idem
> Marko support

- index.js
- test.js
note: 
line 54: while i was inspecting, the content-type prop was all lower-case.  That's why this is all lower-case, opposed to "Content-Type".
> added view eval to check for content-type before assigning a default

- README.md
Now it's not point to the root directory
> Fix templates dir

- index.js
- test.js
I find that in my old code if I use nunjucks' extends tag it will give a error because template path not given so I added it and fixed wrong test case.
> Pass templatesDir to nunjucks to let extends work.

- README.md
- example-ejs-with-some-options.js
- index.js
- package.json
- tap-snapshots/test-with-snapshot.js-TAP.test.js
- templates/index-linking-other-pages.ejs
- templates/index.ejs
- test-with-snapshot.js
- test.js
Issue#29, set default charset and simplify/update tests and example applications, pages and docs - second try.
Note that his time I added even some commented line in sources, just a minimal sample (to try to clarify usage of some options).
> Issue#29, set default charset - second try

- example-ejs-with-some-options.js
- package.json
- test-with-snapshot.js
- test.js
Updated dependencies for nunjucks and other packages, and update sources to new (stricter) rules of 'standard'.
@mcollina Matteo sorry for now I just stay on last Fastify 0.x (0.43.0), is it good the same ?
Last, in this PR should I update plugin release too (for example to '0.8.0') ?
Thanks a lot,
Sandro
> issue38, update dependencies for nunjucks and others

- index.js
- templates/index-with-no-data.ejs
- test.js
This makes passing data optional as mentioned by #52.
> Allow no data to be passed

- package.json
All seems to work with this (latest release); then other greenkeeper branches for previous releases could be deleted. Bye
> chore(package): update marko to version 4.14.23

- README.md
- index.js
- test.js
I am currently staging a project for production that uses this plugin and ran into this bug.
It seems to only affect `fastify.view()` and not `reply.view()`. I stumbled upon it through the approach of supporting async/await mentioned here https://github.com/fastify/point-of-view/issues/87#issuecomment-465327052.
Regarding testing, I had to add an option to force the plugin into production mode. The tests were setup to fail and then clear as soon as the bug was fixed.
> Fix for production view cache issue

- index.js
- templates/layout.pug
- templates/sample.pug
- test/test-pug.js
Currently, relative includes using Pug are not working.
To reproduce, let's create two templates and the configuration:
```pug
//- templates/layout.pug
doctype html
html(lang='en')
head
meta(charset='utf-8')
title= title
body
block content
```
```pug
//- templates/index.pug
extends layout
block content
h1= title
h2 Welcome to #{title}!
```
```js
// app.js
fastify.register(require('point-of-view'), {
engines: {
pug: require('pug'),
},
templates: 'templates',
includeViewExtension: true,
})
fastify.get('/', (response, reply) => {
reply.view('index', { title: 'Fastify' })
})
```
For now, it just throws telling that you should [provide a `filename` option](https://pugjs.org/api/reference.html#options) when rendering in order for Pug to resolve the relative include (`basedir` is needed for …
> Fix relative include for Pug

- index.js
- templates/index-bare.html
- test/test-art-template.js
- test/test-ejs-mate.js
- test/test-ejs.js
- test/test-handlebars.js
- test/test-marko.js
- test/test-mustache.js
- test/test-nunjucks.js
- test/test-pug.js
Currently the data-parameter of
.view(page, data)
is mandatory even tough the data object gets reassigned to an empty object in combination with the `defaultContext`-object. Omitting the data-parameter raises the `Missing Data`-error.
I removed the data-parameter from the `Missing Data`-validation to remove the necessity to provide an empty data-object.
- The change is not benchmarked, since i removed one Short Circuit Condition.
- The change is not being documented, since the data-parameter seems not being explicitly documented anywhere.
> Make data-parameter of view(page, data) optional

- README.md
- index.d.ts
- package.json
- templates/index-with-includes-and-attribute-missing.ejs
- templates/index-with-includes-one-missing.ejs
- templates/index-with-includes.ejs
- types.test.ts
Hi all,
this PR  set in an explicit way latest EJS release and update related info in the README and in sample templates, so templates/fragments works even with latest EJS release.
Note that the problem is not visible in tests, but only executing npm custom command 'example-with-options' and browse into linked pages, and I think it's caused by some changes in latest ejs release (good relative path between pages and fragments).
Last, tests currently are failing due to a TypeScript error (it was the same even before my changes), if someone has some hint I can add even that fix in this PR.
For info tell me.
Bye
> Fix ejs templates relative paths (in doc and examples) for latest EJS release

- README.md
A quick update on the usage readme to include an async example and the requirement to return the reply object.
> Add async example in usage section

- README.md
- index.d.ts
Support for `ejs-mate` has been dropped in https://github.com/fastify/point-of-view/pull/157, but it was still appearing on the front page. This PR removes it from the `README.md` file, and also the typing.
Note that there is only a trivial code change. I only have a puny laptop so I will not even attempt `npm run benchmark` :sweat_smile:
- [-] tests and/or benchmarks are included
> Document dropping support for ejs-mate.

- index.d.ts
- test/index.test-d.ts
Added twig to the definitions file. 
Fixes unsupported type when using point-of-view with typescript.
- [-] tests and/or benchmarks are included
- [-] documentation is changed or added
> add twig engine to definitions

- README.md
- index.d.ts
- index.js
- test/test-art-template.js
- test/test-ejs.js
- test/test-handlebars.js
- test/test-marko.js
- test/test-mustache.js
- test/test-nunjucks.js
- test/test-pug.js
- test/test-twig.js
I've added feature to override properties from defaultContext with ones from reply.locals.
Not all tests are updated yet, because I want someone to check implementation first.
> Add ability to override defaultContext properties with ones from reply locals

- README.md
- index.d.ts
- index.js
- package.json
- test/index.test-d.ts
- test/test-art-template.js
- test/test-ejs.js
- test/test-handlebars.js
- test/test-marko.js
- test/test-mustache.js
- test/test-nunjucks.js
- test/test-pug.js
- test/test-twig.js
According to the documentation, options `root` and `viewExt` can be provided while registering the plugin with fastify. However, in a TS codebase, providing these options throws an error since these options are not defined on `PointOfViewOptions` interface.
This PR adds `root` and `viewExt` as optional string properties on `PointOfViewOptions`.
> Added missing root and viewExt properties to typescript definitions

- example-marko.js
- index.js
- test/test-marko.js
Marko template engine's loader supports loading template from memory, which is important for the use case of pre-loading template from central repository like AWS, edited through web editor.
This pull request supports this use case by testing if `templateSrc` exists in `opts` and pass it to `marko` loader if it exists.
Developer using this model should pass pre-loaded template source as `templateSrc` property of `opts`.
The `path` for template page should still be provided and the folder should still exist or be created for marko loader's search of components. It has been tested with the sample `fastify` integration code of `marko`.
`npm run test` result:
```
Suites:   13 passed, 13 of 13 completed
Asserts:  1027 passed, of 1027
Time:     4s
```
File               |  % Stmts | % Branch | …
> Support load template from memory for marko template engine

- index.d.ts
Add missing type for liquidjs engine
There is a benchmark folder though there is no benchmark script so haven't run `npm run benchmark`. Am I missing something?
> Add type for liquidjs engine

- index.js
- test/test-eta.js
Fix for Eta template engine issue: cache instance were always replaced with the default one
> fix(Eta): cache instance provided through options is ignored and replaced with the default one

- README.md
- index.js
- test/test.js
- Name the plugin 'point-of-view' so it can be required as a [plugin dependency](https://github.com/fastify/fastify-plugin#dependencies).
- Add instructions for requiring `point-of-view` as a plugin dependency in `README.md`.
-  Create test for name registration
> Add name to plugin (#1)

- README.md
- index.js
- test/test.js
```
fastify.register(require('../index'), {
engine: { ejs: ejs },
....,
propertyName: 'mobile'
})
fastify.register(require('../index'), {
engine: { ejs: ejs },
....,
propertyName: 'desktop'
})
reply.mobile('index-for-layout.ejs', { text })
reply.desktop('index-for-layout.ejs', { text })
```
> Add prefix

- index.js
- templates/layout.dot
- test/test-dot.js
- test/test.js
> dot: layout option

- index.d.ts
- test/index.test-d.ts
Hey,
this PR adds the `propertyName` option to the PointOfViewOptions interface.
> Add propertyName to PointOfViewOptions interface

- README.md
- index.d.ts
- package.json
- test/index.test-d.ts
In practice it turned out that it is better when there are no definitions for `locals` at all. If necessary, it is easier to determine without conflicts directly in the code
```typescript
declare module 'fastify' {
interface FastifyReply {
locals: Partial<{ assetsManifest: AssetsManifest }> | undefined;
}
}
```
```typescript
server.addHook('preHandler', (request: FastifyRequest, reply: FastifyReply, done: HookHandlerDoneFunction) => {
if (typeof reply.locals === 'undefined') {
reply.locals = {};
}
reply.locals.assetsManifest = assetsManifest();
done();
});
```
> Removed the definition of locals from index.d.ts

- index.js
- test/test-liquid.js
Fix for #243. When the liquidjs engine throws an error the scope of the catch block has `reply.send` as undefined. this swallows the liquidjs error. This PR fixes the scoping issue and allows liquid js errors to be sent by fastify correctly.
I'm not sure why https://github.com/fastify/point-of-view/blob/master/test/test-liquid.js#L439 doesn't catch this error. the error my code actually was getting from liquidjs was `err.message = 'ENOENT: Failed to lookup "${file}" in "${roots}"';` I added a test to check this error but I couldn't make it fail before I made the change so not sure if it really helps.
> correctly scope liquidjs errors

- index.js
- test/test-eta.js
Hello maintainers,
While using this plugin with the https://github.com/eta-dev/eta template engine, I noticed that `NODE_ENV=production` never cached the templates.
After some digging I found the culprit:
* `point-of-view` never sends the `{ cache: true }` option to the `eta` engine
**This pull request solves this.**
```js
app.register(require("point-of-view"), {
engine: {
eta: require("eta")
},
options: {
cache: true // This variable is now set by NODE_ENV=production
}
});
```
It can also be enabled by passing `production: true` to the engine.
Rendering a simple template with `NODE_ENV=production`
```js
// index.js
app.register(require("point-of-view"), {
engine: {
eta: require("eta")
}
});
app.get("/", async (req, res) => {
res.view("view", {
items: ["a", "b", "c"]
});
});
// view.eta …
```
> Pass cache option to eta engine

- README.md
- index.d.ts
- test/index.test-d.ts
I missed the ability to add typings to the view data-parameter. So with this change, it is possible to provide view a type, as I would expect.
This change is non breaking.
So what does it do exactly? 
If you provide a type, which has to be an Object-Interface, it makes the data-parameter mandatory and the provided data has to be of shape of that interface. So if you change the interface and miss to adapt the change in the view then typescript screams at you :).
> typescript: Add a generic type to .view

- README.md
> Fixes levels within "Miscellaneous"

- README.md
- index.js
- test/helper.js
- test/test-ejs.js
- test/test-mustache.js
> Exclude paths from html minification #200

- index.js
- templates/partial-1.mustache
- templates/partial-2.mustache
- test/test-handlebars.js
- test/test-mustache.js
While using `point-of-view` I discovered a bug in the cache key generation for partials.
A minimal, reproducible test case has been created in https://github.com/mroderick/point-of-view-bug.
This PR fixes that bug.
The cache key has to consider `page`, `partials` and `requestedPath` to be usable. Ignoring any of these values will result in a key that is too broad, which will result in invalid cache hits.
Note: because `requestedPath` is used for determining whether
minification should be used on the content, it also has to be used in
the cache key.
As below
```js
if (useHtmlMinification(globalOptions, requestedPath)) {
data = globalOptions.useHtmlMinifier.minify(data, globalOptions.htmlMinifierOptions || {})
}
```
| variable | value |
|----------|-------|
| page     | …
> Create a precise cache key for partials for LRU

- index.js
Hi,
I've just started playing around with fastify & nunjucks as I'd like to use it for a project, but noticed the performance seemed slow. Had a poke around and point-of-view is setting up the nunjucks environment on each request, which is expensive, so I've made a change to set it up on load.
Here are some before and after autocannon numbers for a simple fastify-cli generated project, rendering a basic nunjucks view:
```
npx autocannon -c 100 -d 10 -p 10 http://localhost:3000/hello
```
```
┌─────────┬────────┬─────────┬─────────┬─────────┬────────────┬────────────┬─────────┐
│ Stat    │ 2.5%   │ 50%     │ 97.5%   │ 99%     │ Avg        │ Stdev      │ Max     │
├─────────┼────────┼─────────┼─────────┼─────────┼────────────┼────────────┼─────────┤
│ Latency │ 560 ms │ 4442 ms │ 7532 ms │ …
```
> perf: setup nunjucks environment on load rather than per request

- README.md
- index.js
- templates/nunjucks-layout/layout.njk
- templates/nunjucks-template/index.njk
- test/test-nunjucks.js
- test/test.js
Hello,
Nunjucks allows you to load templates from mulitple paths, a feature I need as I will be rendering views local to the project, but they will be utilising shared components from an npm module. So I've added support in this PR.
Thanks!
> feat: allow passing array of template paths for nunjucks engine

- index.js
- test/test-ejs-async.js
#314 did not fully cover async rendering with ejs: when caching is applied (in production mode), the error from #312 reappears.
The reason for that is **await** being applied to the asynchronous template only in **readCallback** which is not called if the template has already been compiled and saved to the cache.
This pull request fixes the issue by also awaiting the template after it is retrieved from the cache.
> Support for async rendering with ejs in production mode

- example-ejs-with-some-options.js
This PR fixes a typo.
`contenxt` -> `context`
> chore: fix typo contenxt -> context

- index.js
- test/test-ejs-async.js
There has been an error overriding async from true to false in the render function. These changes should fix that.
Now it is possible to specify async: true in global options, and async: false as a local option. The overriding behavior now works correctly: local option async: false will be used.
> EJS: Fixed local override of async from true to false

- README.md
> docs: update references to old point-of-view module

- README.md
- benchmark/fastify.js
- example-async.js
- example-ejs-with-some-options.js
- example.js
> chore: replace use of deprecated variadic `listen()`

- README.md
- package.json
When we dropped the support for marko, the only relevant place where we used useHtmlMinifyStream was gone. This PR removes the documentation of this not anymore existing option.
Also removes html-minify-stream as devDependency as it was probably used for marko tests...
> remove references to useHtmlMinifyStream

- index.js
Following the deprecation warning on fastify: https://github.com/fastify/fastify/blob/7ffefaf272e1b0da5c0889e0c7c54ac8203756f2/lib/request.js#L159 changed it to use `fastify.request.routerPath`
> chore: replace use of deprecated fastify.request.context

- index.js
- test/test-nunjucks.js
It allows custom `Content-Type` response header for Nunjucks template engine.
Closes #353
> Allow custom `Content-Type` header for Nunjucks

- index.js
- types/index-global-layout.test-d.ts
- types/index.d.ts
- types/index.test-d.ts
> nodenext compatibility

- types/index.d.ts
- types/index.test-d.ts
> Type of templates property in PointOfViewOptions show allow arrays

- index.js
The options callback for setting globals/filters on the nunjucks environment was being executed on request setting the same globals/filters over and over again. I've moved the code up to only execute on plugin load.
Don't think any new tests are needed.
> refactor: set nunjucks environment globals on load not per request

- index.js
- test/test-handlebars.js
In #147, changes were made to get Handlebars to throw errors correctly, with a test. However, in the case where Handlebars was used with a global layout provided, things were still broken. The withLayout helper threw an error directly in the middle of callback code. This PR provides a test demonstrating the failure along with the fix of that mistake.
> Fix hbs with layout not throwing errors correctly

- index.js
Import functions all in one go rather than successive `require()` calls.
Probably the tiniest perf improvement but cba to bench for a quectosecond improvement.
Saves a few bytes regardless.
> refactor(index): destruct module imports

- test/test-eta.js
See https://github.com/fastify/fastify-helmet/issues/236
> test(eta): replace `typeof` undefined check

- index.js
- package.json
- test/test-handlebars.js
- test/test-mustache.js
- test/test-pug.js
- types/index.d.ts
In preparation for potentially migrating from `hashlru` to `toad-cache` -- encapsulate the lru as a decorator.
This will:
- make the tests agnostic to underlying cache implementations
- aid in benchmarking differences between cache implementations
- drop a devDependency
|Benchmark||Node 18 PR|Node 18 Base||Node 20 PR|Node 20 Base||Node 21 PR|Node 21 Base|
|-|-|-|-|-|-|-|-|-|-|
|express.js||8351|8231||8815|8591||8439|8447|
|fastify.js||42975|41247||43391|42687||42271|42463|
|fastify-art.js||9511|9431||10487|**11567**||9287|9271|
|fastify-dot.js||47199|46367||47615|46751||47839|46975|
|fastify-eta.js||27199|27007||30095|29327||**37695**|35327|
|fastify-pug.js||45183|45759||46367|44735||46719|46559|
|fastify-twig.js||30175|**35423**||38911|38335||40831|39167| …
> refactor: encapsulate cache as decorator

- index.js
- package.json
Swap in `toad-cache` for `hashlru` as requested here: https://github.com/fastify/point-of-view/pull/414#issuecomment-1965962275
|Benchmark||Node 18 PR|Node 18 Base||Node 20 PR|Node 20 Base||Node 21 PR|Node 21 Base|
|-|-|-|-|-|-|-|-|-|-|
|express.js||8943|8871||**9423**|8799||9183|9151|
|fastify.js||35263|**42847**||45151|44095||43007|42079|
|fastify-art.js||10167|9711||11671|12007||9431|9023|
|fastify-dot.js||49887|48895||48639|48671||47039|47487|
|fastify-eta.js||27999|28111||29983|30767||37151|35647|
|fastify-pug.js||42079|**46751**||49055|48127||35647|**46271**|
|fastify-twig.js||32015|**36639**||40063|40095||33631|**37759**|
|fastify-liquid.js||6975|6975||7363|**8335**||7611|7583|
|fastify-mustache.js||33535|32799||34943|34751||33855|34303| …
> chore: swap toad cache for hashlru

- index.js
- test/test-handlebars.js
Specifying a layout on render causes a synchronous `fs.accessSync` on every request. Cache the result of these lookups in LRU to avoid duplicate blocking checks.
```
fastify-ejs-local-layout.js: 84885.34 req/s
fastify-ejs-global-layout.js: 115680 req/s
```
```
fastify-ejs-local-layout.js: 114592 req/s
fastify-ejs-global-layout.js: 116917.34 req/s
```
> perf: cache layout access check

- .taprc
- index.js
- package.json
- test/test-import-engine.mjs
With commonjs it was common to require the engine in the options, and the current readme suggests this usage:
```js
fastify.register(require("@fastify/view"), {  engine: { ejs: require("ejs") } });
```
With modules, the same usage wasn't previously possible, because the inline import returns a promise.
```mjs
app.register(import('@fastify/view'), { engine: { ejs: import('ejs') } })
// results in error later that "engine.compile is not a function"
```
So instead you had to await that import inline, and delay setting up further plugins:
```mjs
app.register(import('@fastify/view'), { engine: { ejs: await import('ejs') } })
```
Since the plugin initialisation is already an async function, it seemed straightforward to just `await` the engine during plugin initialisation instead, which will …
> suggestion: await engine to support inline engine import in options
